# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceKGServer', '0002_auto_20160727_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='category_id',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ServiceKGServer.Category'),
        ),
    ]
