# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceKGServer', '0004_auto_20160731_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='phone_three',
            field=models.IntegerField(null=True, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d 3'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='phone_two',
            field=models.IntegerField(null=True, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d 2'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='description',
            field=models.CharField(max_length=10000, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
    ]
