# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceKGServer', '0006_auto_20160801_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='order',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u0426\u0435\u043d\u0430 \u0443\u0441\u043b\u0443\u0433\u0438'),
        ),
    ]
