# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceKGServer', '0008_auto_20160804_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='from_datetime',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='to_datetime',
        ),
    ]
